name: leigod auto pause action
on:
  push:
  schedule:
    # 定时任务，北京时间3点执行任务 19 + 8 = 27 % 24 = 3
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: npm install
        run: |
          npm install
      - name: run script
        run: |
          node index.js
        env:
          USERNAME_ARR: ${{ secrets.USERNAME_ARR }}
          PASSWORD_ARR: ${{ secrets.PASSWORD_ARR }}
